# -*- coding: utf-8 -*-
"""Exp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxpDLeGOW37jDtmeK4MgyzZ69kIyPD01
"""

# To find wheather using Quadratic
x = 4.5
a = 5
b = 4
c = 6
y = a*x*x + b*x + c
print(a," ",b," ",c," ")
print("Y = ",y)